export { Header } from "./header/header";
export { Menu } from "./menu/menu";
export { Question } from "./question/question";
export { Trivia } from "./trivia/trivia";
export { Answer } from "./answer/answer";
export { Spinner } from "./spinner/spinner";
export { TopScores } from "./top-scores/top-scores";
export { About } from "./about/about";
export { BackArrow } from "./back-arrow/back-arrow";
